[package]
name = "mindmap_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = {version = "0.21.0", features = ["csr"]}
stylist = { version = "0.13.0", features = ["yew_integration"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "HtmlElement"] }